# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blan_B' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Blan_B


pod 'Firebase/Core'

  target 'Blan_B-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Blan_BTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
